// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAjkx2lEwqB1r_Ot6yWyCkz6zqu7SA5Os',
    appId: '1:1033391796294:android:cad44f49ad86c19f35da47',
    messagingSenderId: '1033391796294',
    projectId: 'grocery-7519c',
    databaseURL: 'https://grocery-7519c-default-rtdb.firebaseio.com',
    storageBucket: 'grocery-7519c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV2mxUFFUlNVbzHP6SEd_4ZXygjP30BU0',
    appId: '1:1033391796294:ios:5c20fc4b776c807335da47',
    messagingSenderId: '1033391796294',
    projectId: 'grocery-7519c',
    databaseURL: 'https://grocery-7519c-default-rtdb.firebaseio.com',
    storageBucket: 'grocery-7519c.appspot.com',
    iosClientId:
        '1033391796294-lkor72is40j5gdhn5bk9e36o1tgmhs3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );
}
